"""
Provides classes for describing :mod:`.corpus` or :mod:`.social` models.

.. autosummary::

   corpus
   social

The purpose of this module is to provide a common way to describe models
generated by various modeling algorithms and their sundry implementations.

To generate models from a :class:`.Corpus` and/or :class:`.GraphCollection`\,
use one of the model :mod:`.managers`\.

All model classes should be subclasses of :class:`.BaseModel`\. It is assumed
that each model describes a set of items (e.g. :class:`.Paper`\s or authors),
a set of dimensions that describe those items (e.g. topics), and a set of
features that comprise those dimensions (e.g. words).

Thus each model subclass should inherit the following methods:

.. autosummary::
   :nosignatures:

   basemodel.BaseModel.item
   basemodel.BaseModel.item_relationship
   basemodel.BaseModel.dimension
   basemodel.BaseModel.dimension_items
   basemodel.BaseModel.dimension_relationship

"""

from corpus import *
from social import *
from basemodel import *